config/routes.rb
Rails.application.routes.draw do
  #top画面のルート
  root to: 'home#top'
  get '/about'=>'home#about'
  get '/learn'=>'home#learn'

  #userデバイスのルート
  devise_for :users, controllers: {
    sessions: "user_devises/sessions",
    registrations: "user_devises/registrations",
    passwords: "user_devises/passwords"
  }
  #userのルート petsとreservationsネスト
  resource :user, only: [:show], shallow: true do
    resources :pets, only: [:index, :create, :edit, :update, :destroy]
    resources :reservations, only: [:index, :create] do
      post 'confirm', on: :collection
      get 'finish', on: :collection
    end
    get 'confirm', on: :collection
    put 'hide', on: :collection
  end

  #hotelのルート(User以外にも閲覧可能) commentsとfavoritesネスト
  resources :hotels, only: [:show, :index], shallow: true do
    resources :hotel_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  #hotel検索のルート
  get 'search' => 'searches#search'

  #ownerデバイス
  devise_for :owners, controllers: {
    sessions: "owner_devises/sessions",
    registrations: "owner_devises/registrations",
    passwords: "owner_devises/passwords"
  }

  #on: :collectionでグループ化
  resource :owner, only: [:show, :edit, :update] do
    get 'confirm', on: :collection
    put 'hide', on: :collection
  end

  namespace :owner do
    get 'home' => 'home#top'
    resources :hotels
    resources :reservations, only: [:index, :destroy]
    resources :users, only: [:show]
  end

  #adminデバイス
  devise_for :admins, controllers: {
    sessions: "admin_devises/sessions",
    registrations: "admin_devises/registrations",
    passwords: "admin_devises/passwords"
  }

  #adminグループアクション
  namespace :admin do
    resources :users, only: [:show, :index, :edit, :update]
    resources :owners, only: [:index, :edit, :update]
    resources :pet_genres, only: [:index, :create, :destroy]
    resources :hotels
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :hotel_comments, dependent: :destroy
  has_many :hotel_genre_relations, dependent: :destroy
  has_many :pet_genres, through: :hotel_genre_relations
  has_many :reservations
  has_many :hotel_images, dependent: :destroy
  belongs_to :owner
  attachment :image
  #refile複数画像投稿用に下記記述
  accepts_attachments_for :hotel_images, attachment: :image
  #バリデーション
  validates :name, presence: { message:"を入力してください"}
  validates :price, presence: { message:"を入力してください"}
  validates :address, presence: { message:"を入力してください"}
  validates :phone_number, presence: { message:"を入力してください"}
  validates :hotel_images, length:{ maximum: 6, message:"は6枚まで投稿可能です" }
  #検索スピードを考慮してexists?を使用
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < ApplicationController
  before_action :authenticate_admin!

  #管理者用のホテル一覧
  def index
    @hotels = Hotel.all.order(created_at: "DESC").page(params[:page]).per(5)
     #indexページにて送られて生きたステータス(is_valid)でホテルを検索
      if params[:is_valid]
        @is_valid = params[:is_valid]
        hotels = Hotel.where(is_valid: @is_valid)
        @hotels = Kaminari.paginate_array(hotels).page(params[:page]).per(5)
     end
  end

  def show
    @hotel = Hotel.find(params[:id])
    @reservations = @hotel.reservations.page(params[:page]).per(5)
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      flash[:success] = "ホテル情報が更新されました"
      @hotels = Hotel.all.page(params[:page]).per(5)
      render "index"
    end
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    if @hotel.destroy
      flash[:success] = "ホテル情報が削除されました。"
      redirect_to admin_hotels_path
    end
  end

  private
  def hotel_params
    params.require(:hotel).permit(:owner_id, :name, :image, :price, :address, :phone_number, :image, :introduction, :is_valid)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  def index
    @pet_genres = PetGenre.all
    #お気に入りが多い順に表示+ステータスが有効なホテルを取得
    @hotel_all = Hotel.where(is_valid: "true").includes(:favorites)#左外部結合でテーブルを結合
    hotels = @hotel_all.sort_by {|hotel| hotel.favorites.count}.reverse#昇順に並べ替え
    @hotels = Kaminari.paginate_array(hotels).page(params[:page]).per(5)#ページネーションのためKaminari利用
    #ペットジャンルで検索+ステータスが有効なホテルを取得
    if params[:pet_genre_id]
      @pet_genre = PetGenre.find_by(id: params[:pet_genre_id])
      @hotel_all = @pet_genre.hotels.where(is_valid: "true").includes(:favorites)
      hotels = @hotel_all.sort_by {|hotel| hotel.favorites.count}.reverse#昇順に並べ替え
      @hotels = Kaminari.paginate_array(hotels).page(params[:page]).per(5)#ページネーションのためKaminari利用
    end
  end

  #(前のバ―ション)hotel一覧をいいね昇順に並べ替え、ホテルのステータスが有効なものだけをhotelsの配列に入れる
  #@hotel_ranks = Favorite.group(:hotel_id).order('count(hotel_id) desc').pluck(:hotel_id)
    #@hotels = []
    #@hotel_ranks.each do |hotel_rank|
      #@hotel = Hotel.find(hotel_rank)
      #if @hotel.is_valid == true
         #@hotels.push(@hotel)
      #end
    #end

  def show
    @hotel = Hotel.find(params[:id])
    #ホテルのステータスが無効なものはページ遷移できない設定(Userのみ)
    if current_owner || current_admin
      @hotel = Hotel.find(params[:id])
    else
      if @hotel.is_valid == false
        flash[:error] = "こちらのホテルは無効です"
        redirect_to hotels_path
      end
    end
    @hotel_comment = HotelComment.new
    @hotel_comments = @hotel.hotel_comments #hotelのidに紐づいたhotels全部
    @reservation = Reservation.new
    @pet_genres = PetGenre.all
    #User以外が閲覧している場合はペット情報を持たない且つ予約不可のため下記で分岐
    if current_user
      @pets = current_user.pets #Userのペット一覧の情報
    end
    #検索に必要な情報をメソッドをつかって検索(中間テーブル活用)
    if params[:pet_genre_id]
      @pet_genre = PetGenre.find_by(id: params[:pet_genre_id])
      hotels = @pet_genre.hotels.where(is_valid: "true")#受け取ったペットIDに基づくHotelをすべて取得+有効(承認済み)のもの
      @hotels = Kaminari.paginate_array(hotels).page(params[:page]).per(5)
      render "index"
    end
  end

private
  def hotel_params
    params.require(:hotel).permit(:owner_id, :name, :image, :price, :address, :phone_number, :image, :introduction, :is_valid)
  end

end

app/controllers/owner/hotels_controller.rb
class Owner::HotelsController < ApplicationController
  before_action :authenticate_owner!

  def new
    @hotel = Hotel.new
    @owner = current_owner
    @hotel.hotel_images.build#関連するモデルを生成するためbuild
  end

  def create
    @hotel = current_owner.hotels.new(hotel_params)
    if @hotel.save
      flash[:success] = "ホテル情報が申請されました！営業日2～3日以内にご連絡差し上げます。"
      redirect_to owner_path
    else
      @hotel.hotel_images.build
      render "new"
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
    @reservations = @hotel.reservations.order(created_at: "DESC").page(params[:page]).per(5)
  end

  def edit
    @hotel = Hotel.find(params[:id])
    if current_owner.id != @hotel.owner.id
    redirect_to owner_path
    end
  end

  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      flash[:success] = "ホテル情報が更新されました！"
      redirect_to owner_path
    else
      render "edit"
    end
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    if @hotel.destroy
      flash[:success] = "ホテル情報が削除されました。"
      redirect_to owner_path
    end
  end

private
  def hotel_params
    params.require(:hotel).permit(:owner_id, :name, :image, :price, :address, :phone_number, :image, :introduction, :is_valid, hotel_images_images: [], pet_genre_ids: [])
  end
end

app/helpers/admin/hotels_helper.rb
module Admin::HotelsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/owner/hotels_helper.rb
module Owner::HotelsHelper
end

app/views/admin/hotels/edit.html.erb
<div class="container">
  <h2><%= @hotel.name %> を編集</h2>
  <h4>ホテルステータスの変更</h4>
  <i>有効にしたホテルは掲載されます。</i>
  <%= form_with model:[@owner, @hotel], url:admin_hotel_path(@hotel), method: :put, local:true do |form| %>

    <%= form.radio_button :is_valid, true,  class: :radio_button %>
    <%= form.label :is_valid, "有効にする" %>

    <%= form.radio_button :is_valid, false,  class: :radio_button %>
    <%= form.label :is_valid, "無効にする" %>

    <div><%= form.submit "編集内容を保存する", class: "btn-sm btn-primary" %></div>

  <% end %>

  <div class="owner_edit_box">

    <p><strong><%= link_to "#{@hotel.owner.name}", edit_admin_owner_path %></strong> 様へ連絡をする</br>電話番号：<%= @hotel.phone_number %></p>

  </div>
</div>

app/views/admin/hotels/index.html.erb
<!--ホテル申請一覧は管理者hotelのIndex-->
<div class="container">
  <p class="text-primary"><%= flash[:success] %></p>
	<!--Hotelの有効、無効で表示を変える-->
	<div>
	  <%= form_with(url: admin_hotels_path, method: :get, local:true) do |form| %>
	    <%= form.select :is_valid, ([["有効(承認済み)","true"],["無効(申請待ち)","false"]]) %>
	    <%= form.submit "表示する", class: "btn-sm btn-warning" %>
	  <% end %>
	</div>

  <!--Hotel一覧もしくは上記で検索した条件(有効・無効)に合うホテル一覧を表示-->
    <% @hotels.each do |hotel| %>
      <div class="hotel_box">
        <%= render partial: 'hotels/hotels', locals: {hotel: hotel} %>
        <% if hotel.is_valid? %>
          <p>有効</p>
        <% else %>
          <p><strong>無効(申請承認待ち)</strong></p>
        <% end %>
        <%= link_to "ホテル編集", edit_admin_hotel_path(hotel), class: "btn btn-success" %>
        <%= link_to "予約確認", admin_hotel_path(hotel), class: "btn btn-warning" %>
      </div>
    <% end %>
  <div class="text-center">
    <%= paginate @hotels %>
  </div>
</div>

app/views/admin/hotels/show.html.erb
<!--各ホテルの予約一覧-->
<div class="container">
  <h4><strong>予約一覧</strong></h4>
    <% @reservations.each do |reservation| %>
      <div class="col-xs-12 reservation-box">
      <%= render partial: 'reservations/all', locals: { reservation: reservation} %>
      <%= link_to "お客様詳細", admin_user_path(reservation.user) %>
      </div>
    <% end %>
  <div class="text-center">
    <%= paginate @reservations %>
  </div>
</div>