config/routes.rb
Rails.application.routes.draw do
  #top画面のルート
  root to: 'home#top'
  get '/about'=>'home#about'
  get '/learn'=>'home#learn'

  #userデバイスのルート
  devise_for :users, controllers: {
    sessions: "user_devises/sessions",
    registrations: "user_devises/registrations",
    passwords: "user_devises/passwords"
  }
  #userのルート petsとreservationsネスト
  resource :user, only: [:show], shallow: true do
    resources :pets, only: [:index, :create, :edit, :update, :destroy]
    resources :reservations, only: [:index, :create] do
      post 'confirm', on: :collection
      get 'finish', on: :collection
    end
    get 'confirm', on: :collection
    put 'hide', on: :collection
  end

  #hotelのルート(User以外にも閲覧可能) commentsとfavoritesネスト
  resources :hotels, only: [:show, :index], shallow: true do
    resources :hotel_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  #hotel検索のルート
  get 'search' => 'searches#search'

  #ownerデバイス
  devise_for :owners, controllers: {
    sessions: "owner_devises/sessions",
    registrations: "owner_devises/registrations",
    passwords: "owner_devises/passwords"
  }

  #on: :collectionでグループ化
  resource :owner, only: [:show, :edit, :update] do
    get 'confirm', on: :collection
    put 'hide', on: :collection
  end

  namespace :owner do
    get 'home' => 'home#top'
    resources :hotels
    resources :reservations, only: [:index, :destroy]
    resources :users, only: [:show]
  end

  #adminデバイス
  devise_for :admins, controllers: {
    sessions: "admin_devises/sessions",
    registrations: "admin_devises/registrations",
    passwords: "admin_devises/passwords"
  }

  #adminグループアクション
  namespace :admin do
    resources :users, only: [:show, :index, :edit, :update]
    resources :owners, only: [:index, :edit, :update]
    resources :pet_genres, only: [:index, :create, :destroy]
    resources :hotels
  end
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :hotels, dependent: :destroy
  validates :name, presence: { message: "を入力してください" }
  validates :phone_number, numericality: {only_integer: true,message:"を入力してください"},format:{with: /\A\d{10,11}\z/,message: "ハイフン無し10桁or11桁で入力して下さい。"}
  validates :email, presence: true, uniqueness: { message:":入力されたアドレスは既に登録されています"}, on: :create
  #{AZ}はハイフン無し
  #退会済みのアカウントをはじく
  def active_for_authentication?
  super && (self.is_valid == true)
  end
end

app/controllers/admin/owners_controller.rb
class Admin::OwnersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @owners = Owner.all.order(created_at: "DESC").page(params[:page]).per(10)
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])
    if @owner.update(owner_params)
      flash[:success] = "更新されました"
      redirect_to admin_owners_path
    else
      render "edit"
    end
  end

  private
  def owner_params
    params.require(:owner).permit(:email, :name, :phone_number, :is_valid)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def top
 end
end

app/controllers/owner/home_controller.rb
class Owner::HomeController < ApplicationController
 def top
 end
end

app/controllers/owner/hotels_controller.rb
class Owner::HotelsController < ApplicationController
  before_action :authenticate_owner!

  def new
    @hotel = Hotel.new
    @owner = current_owner
    @hotel.hotel_images.build#関連するモデルを生成するためbuild
  end

  def create
    @hotel = current_owner.hotels.new(hotel_params)
    if @hotel.save
      flash[:success] = "ホテル情報が申請されました！営業日2～3日以内にご連絡差し上げます。"
      redirect_to owner_path
    else
      @hotel.hotel_images.build
      render "new"
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
    @reservations = @hotel.reservations.order(created_at: "DESC").page(params[:page]).per(5)
  end

  def edit
    @hotel = Hotel.find(params[:id])
    if current_owner.id != @hotel.owner.id
    redirect_to owner_path
    end
  end

  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      flash[:success] = "ホテル情報が更新されました！"
      redirect_to owner_path
    else
      render "edit"
    end
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    if @hotel.destroy
      flash[:success] = "ホテル情報が削除されました。"
      redirect_to owner_path
    end
  end

private
  def hotel_params
    params.require(:hotel).permit(:owner_id, :name, :image, :price, :address, :phone_number, :image, :introduction, :is_valid, hotel_images_images: [], pet_genre_ids: [])
  end
end

app/controllers/owner/users_controller.rb
class Owner::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :authenticate_owner!

  def show
    @owner = current_owner
    @hotels =@owner.hotels.order(created_at: "DESC").page(params[:page]).per(5)
  end

  def confirm
    @owner = current_owner
    if current_owner.id != @owner.id
      redirect_to owner_path(@owner)
    end
  end

  def hide
    @owner = current_owner
    #hideアクションでis_vaildカラムをfalseへupdate
    if @owner.update(is_valid: false)
       reset_session
       flash[:success] = "ありがとうございました。またのご利用を心よりお待ちしております。"
       redirect_to owner_home_path
    else
       render edit_owner_registration_path
    end
  end

  private
  def owner_params
    params.require(:owner).permit(:email, :name, :phone_number, :is_valid)
  end
end

app/helpers/admin/owners_helper.rb
module Admin::OwnersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/owner/home_helper.rb
module Owner::HomeHelper
end

app/helpers/owner/hotels_helper.rb
module Owner::HotelsHelper
end

app/helpers/owner/reservations_helper.rb
module Owner::ReservationsHelper
end

app/helpers/owner/users_helper.rb
module Owner::UsersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owner/home/top.html.erb
<div class="jumbotron">
  <div class="container">
    <p class="text-primary"><%= flash[:success] %></p>
 	  <h1>As your best partner</h1>
 	  <p>このサイトでは、ホテルの審査過程を設けているため、お客様の信頼を得ています。<br>ペットのためを考えるお客様の応援ができるよう、パートナーとして一緒に素敵な環境づくりができればと存じます。</p>
 	  <%= link_to new_owner_registration_path do %>
    <button class="btn btn-lg btn-warning">ホテルの登録を始める</button>
    <% end %>
    <%= link_to new_owner_session_path do %>
    <button class="btn btn-lg">ログイン</button>
    <% end %>
  </div>
</div>

<!--main-->
<hr>
<div class="col-xs-12 col-sm-8 col-sm-offset-4 step">
  <h1><span class="far fa-lightbulb faa-ring animated"></span>ホテル掲載までのSTEP</h1>
</div>

<div class="container">
  <!--main1-->
  <div class="row owner_main">
    <%= image_tag 'pets.jpg', format: 'jpg', size: "300x300", class: "owner_main_img col-xs-12 col-sm-4" %>
    <div class="col-xs-12 col-sm-8">
      <ul class="owner_step">
  	    <li><strong> Step1．無料会員登録</strong></li>
        <p class="col-xs-12 col-sm-8">無料で会員登録していただくことが可能です。</br>まずは1分程度の会員登録をお願いします。</p>
      </ul>
    </div>
  </div>

  <!--main2-->
  <div class="row owner_main">
  <hr>
    <div class="col-xs-12 col-sm-8">
      <ul class="owner_step">
  	    <li><strong> Step2．ホテル申請</strong></li>
        <p class="col-xs-12 col-sm-8">ホテルご申請後、Cadogが2～3日で審査いたします。</p>
      </ul>
    </div>
    <div><%= image_tag 'Catsafe.jpg', format: 'jpg', size: "400x300", class: "owner_main_img col-xs-12 col-sm-4" %></div>
  </div>

  <!--main3-->
  <div class="row owner_main">
  <hr>
    <%= image_tag 'book_dog.jpg', format: 'jpg', size: "300x300", class: "owner_main_img col-xs-12 col-sm-4" %>
    <div class="col-xs-12 col-sm-8">
      <ul class="owner_step">
        <li><strong> Step3．掲載！</strong></li>
        <p class="col-xs-12 col-sm-8">ステータスが承認済みになった時点で掲載開始となります。</p>
      </ul>
    </div>
  </div>
</div>