config/routes.rb
Rails.application.routes.draw do
  #top画面のルート
  root to: 'home#top'
  get '/about'=>'home#about'
  get '/learn'=>'home#learn'

  #userデバイスのルート
  devise_for :users, controllers: {
    sessions: "user_devises/sessions",
    registrations: "user_devises/registrations",
    passwords: "user_devises/passwords"
  }
  #userのルート petsとreservationsネスト
  resource :user, only: [:show], shallow: true do
    resources :pets, only: [:index, :create, :edit, :update, :destroy]
    resources :reservations, only: [:index, :create] do
      post 'confirm', on: :collection
      get 'finish', on: :collection
    end
    get 'confirm', on: :collection
    put 'hide', on: :collection
  end

  #hotelのルート(User以外にも閲覧可能) commentsとfavoritesネスト
  resources :hotels, only: [:show, :index], shallow: true do
    resources :hotel_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  #hotel検索のルート
  get 'search' => 'searches#search'

  #ownerデバイス
  devise_for :owners, controllers: {
    sessions: "owner_devises/sessions",
    registrations: "owner_devises/registrations",
    passwords: "owner_devises/passwords"
  }

  #on: :collectionでグループ化
  resource :owner, only: [:show, :edit, :update] do
    get 'confirm', on: :collection
    put 'hide', on: :collection
  end

  namespace :owner do
    get 'home' => 'home#top'
    resources :hotels
    resources :reservations, only: [:index, :destroy]
    resources :users, only: [:show]
  end

  #adminデバイス
  devise_for :admins, controllers: {
    sessions: "admin_devises/sessions",
    registrations: "admin_devises/registrations",
    passwords: "admin_devises/passwords"
  }

  #adminグループアクション
  namespace :admin do
    resources :users, only: [:show, :index, :edit, :update]
    resources :owners, only: [:index, :edit, :update]
    resources :pet_genres, only: [:index, :create, :destroy]
    resources :hotels
  end
end

app/models/hotel_comment.rb
class HotelComment < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
  #バリデーション
  validates :comment, presence: { message:"を入力してください"}
end

app/controllers/hotel_comments_controller.rb
class HotelCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @hotel = Hotel.find(params[:hotel_id])
    @comment = @hotel.hotel_comments.new(hotel_comment_params)
    @comment.user_id = current_user.id
  end

  def destroy
    @hotel_comment = HotelComment.find(params[:id])
    if @hotel_comment.user == current_user
       @hotel_comment.destroy
    end
    @hotel = Hotel.find(@hotel_comment.hotel_id)#非同期の変数のため
  end

  private
  def hotel_comment_params
    params.require(:hotel_comment).permit(:comment, :user_id, :hotel_id)
  end
end

app/helpers/hotel_comments_helper.rb
module HotelCommentsHelper
end

app/views/hotel_comments/_hotelcomment.html.erb
<h4><strong>コメント一覧<strong></h4>
  <% hotel_comments.each do |hotel_comment| %>
    <div class="row">
    <hr>
      <div class="col-xs-9">
        <p><%= hotel_comment.user.family_name %>さん   <%= hotel_comment.comment %></p>
      </div>
      <div class="col-xs-3">
      <!--コメント投稿者へのみ削除ボタンを表示-->
      <% if hotel_comment.user == current_user %>
        <!--非同期のLocal変数のため削除リンクにて、hotel_comment.hotelでhotelのidを渡す-->
        <%= link_to '削除', hotel_comment_path(hotel_comment, hotel_comment.hotel), class: "btn-sm btn-danger", method: :delete, remote: true %>
      <% end %>
      </div>
    </div>
  <% end %>

app/views/hotel_comments/create.js.erb
/*コメントの部分更新。createアクションが始動された際、コメント部分テンプレートのみを更新。*/
$("textarea").val('')
$("#hotelcomments").html("<%= j(render partial: 'hotel_comments/hotelcomment', locals: {hotel_comments: @hotel.hotel_comments}) %>");

app/views/hotel_comments/destroy.js.erb
/*コメントの部分更新。createアクションが始動された際、コメント部分テンプレートのみを更新。*/
$("#hotelcomments").html("<%= j(render partial: 'hotel_comments/hotelcomment', locals: {hotel_comments: @hotel.hotel_comments}) %>");